name: Build Check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "main"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@deepcrawl"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore keys from cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn prettier:check

      - name: Lint
        run: yarn lerna run --since $BASE_BRANCH --concurrency 1 --stream lint:check

      - name: Test
        run: yarn lerna run --since $BASE_BRANCH --concurrency 1 --stream test:ci

      - name: Build @deepcrawl/test-cli executables
        run: yarn build:executables
        working-directory: packages/test-cli
